Use mapfile to split command output into an array, per SC2207

diff --git a/tpms-helper b/tpms-helper
--- a/tpms-helper
+++ b/tpms-helper
@@ -15,8 +15,8 @@ runsdr="rtl_433 -M level -f 315000000 -F json -T 60 -R 110 -Y minlevel=-1.0"
 for ((i = 0; i < ${#WHEELS[@]}; i++)); do
     echo "Please place sensor at ${WHEELS[$i]}"
     # begin listening for PMV-107J sensors on 315 MHz
-    IDS=( $($runsdr | grep "{*}" | jq '.id') ) || { echo "Could not connect to RTL-SDR!" >&2; exit 1; }
-    for ID in ${IDS[@]}; do
+    mapfile -t MYIDS < <({ $runsdr || { echo "Could not connect to RTL-SDR!" >&2; exit 1; } } | grep "{*}" | jq '.id')
+    for ID in "${IDS[@]}"; do
         echo "Found sensor with ID: $ID"
     done
 done
