store full json for each signal, not just id

diff --git a/tpms-helper b/tpms-helper
--- a/tpms-helper
+++ b/tpms-helper
@@ -19,16 +19,20 @@ for ((i = 0; i < ${#WHEELS[@]}; i++)); do
     echo -e "\e[32mPlease place sensor at ${WHEELS[$i]} wheel!\e[0m"
     # begin listening for PMV-107J sensors on 315 MHz
     echo -e "\e[32mRunning rtl_433...\e[0m"
-    mapfile -t IDS < <( output=$($RUNSDR) || { echo -e "\e[31mCould not connect to RTL-SDR!\e[0m" >&2; exit 1; }  && echo "$output" | grep "{*}" | jq '.id')
-    if [[ ${#IDS[@]} -gt 1 ]]; then
-        echo -e "\e[33mReceived signals from multiple sensors at ${WHEELS[$i]} wheel\e[0m"
-        for ID in "${IDS[@]}"; do
-            echo "Found sensor with ID: $ID"
+    mapfile -t SIGNALS < <( output=$($RUNSDR) || { echo -e "\e[31mCould not connect to RTL-SDR!\e[0m" >&2; exit 1; }  && echo "$output" | grep "{*}")
+    if [[ ${#SIGNALS[@]} -gt 1 ]]; then
+        echo -e "\e[33mReceived signals from multiple sensors at ${WHEELS[$i]} wheel.\e[0m"
+        for SIGNAL in "${SIGNALS[@]}"; do
+            ID=$(echo "$SIGNAL" | jq ".id")
+            RSSI=$(echo "$SIGNAL" | jq ".rssi")
+            echo "Found sensor with ID $ID, signal strength is $RSSI"
         done
-    elif [[ ${#IDS[@]} == 1 ]]; then
-        echo -e "\e[32mReceived signals from one sensor at ${WHEELS[$i]} wheel\e[0m"
-        echo "Found sensor with ID: ${IDS[0]}"
-    elif [[ ${#IDS[@]} == 0 ]]; then
-        echo -e "\e[31mReceived no signals at ${WHEELS[$i]} wheel\e[0m"
+    elif [[ ${#SIGNALS[@]} == 1 ]]; then
+        echo -e "\e[32mReceived signals from one sensor at ${WHEELS[$i]} wheel.\e[0m"
+        ID=$(echo "${SIGNALS[0]}" | jq ".id")
+        RSSI=$(echo "${SIGNALS[0]}" | jq ".rssi")
+        echo "Found sensor with ID $ID, signal strength is $RSSI"
+    elif [[ ${#SIGNALS[@]} == 0 ]]; then
+        echo -e "\e[31mReceived no signals at ${WHEELS[$i]} wheel.\e[0m"
     fi
 done
